-- =============================================================================
-- _clipboard.lua — clipvault clipboard manager
--
-- This is the Lua equivalent of the block generated by enable-clipboard.zsh.
-- That generator must eventually emit this file instead of _clipboard.conf.
-- =============================================================================

local variables = __require("_variables")

local environment = table.concat({
  "env",
  "CLIP_CAP=200",
  "CLEAR_DAYS=3",
  "POLL_MS=1500",
  "PRUNE_EVERY_S=10",
  "CLEAR_CHECK_EVERY_S=30",
  "RESTART_WLPASTE_EVERY_S=0",
  "PRUNE_CAP=" .. variables.home .. "/.local/bin/clipvault-prune-cap",
  "PERIODIC_CLEAR_STAMP=" .. variables.home .. "/.local/state/clipvault-setup/last_clear.ts",
}, " ")

hl.on("hyprland.start", function()
  hl.exec_cmd(environment .. " " .. variables.home .. "/.local/bin/clipvault-watchers")
end)

hl.bind(variables.mod .. " + x", hl.dsp.exec_cmd("clipvault-wofi"))
hl.bind(
  variables.mod .. " + SHIFT + x",
  hl.dsp.exec_cmd(environment .. " " .. variables.home .. "/.local/bin/clipvault-kick")
)
