# =============================================================================
# hyprsunset.conf — automatic night protection
# =============================================================================

profile {
    time = 05:00
    identity = true
}

profile {
    time = 21:00
    temperature = 3500
}