_powyx_reject_unsafe_remove_path() {
    local path="$1"

    [[ -n "$path" ]] || _powyx_error "refusing to remove empty path"
    [[ "$path" = /* ]] || _powyx_error "refusing to remove relative path: $path"
    [[ "$path" != "/" ]] || _powyx_error "refusing to remove /"
    [[ "$path" != "$HOME" ]] || _powyx_error "refusing to remove home directory"
}

_powyx_remove_tree() {
    local path="$1"

    _powyx_reject_unsafe_remove_path "$path"
    [[ -e "$path" ]] || return 0
    rm -rf -- "$path"
}

_powyx_build_installed_binary() {
    local output="$1"
    local entrypoint="$POWYX_REPO_ROOT/package/powyx"

    if ! {
        printf '#!/usr/bin/env bash\n'
        printf 'set -euo pipefail\n\n'
        printf '# Generated by package/install. Do not edit.\n\n'

        cat "$POWYX_REPO_ROOT/package/lib/_core.sh"
        printf '\n'

        cat "$POWYX_REPO_ROOT/package/lib/_pkg.sh"
        printf '\n'

        awk '
            index($0, "(($# == 0)) || _powyx_error") == 1 {
                emit = 1
            }

            emit {
                print
            }

            END {
                if (!emit)
                    exit 64
            }
        ' "$entrypoint"
    } > "$output"; then
        rm -f -- "$output"
        _powyx_error "failed to build installed binary"
    fi

    if ! bash -n "$output"; then
        rm -f -- "$output"
        _powyx_error "generated binary failed syntax validation"
    fi

    chmod 0755 "$output"
}

_powyx_restore_previous_share() {
    _powyx_remove_tree "$POWYX_SHARE_DIR"

    if [[ -e "$POWYX_PREVIOUS_DIR" ]]; then
        mv "$POWYX_PREVIOUS_DIR" "$POWYX_SHARE_DIR" || _powyx_error "failed to restore previous share files"
    fi
}

_powyx_install_files_atomically() {
    local staged_bin="$POWYX_BIN_DIR/.powyx.stage.$$"

    _powyx_remove_tree "$POWYX_STAGE_DIR"
    _powyx_remove_tree "$POWYX_PREVIOUS_DIR"
    rm -f -- "$staged_bin"

    mkdir -p "$POWYX_BIN_DIR"
    _powyx_build_installed_binary "$staged_bin"

    if ! {
        mkdir -p "$POWYX_STAGE_DIR"
        cp -a "$POWYX_REPO_ROOT/src" "$POWYX_STAGE_DIR/src"
        cp -a "$POWYX_REPO_ROOT/icons" "$POWYX_STAGE_DIR/icons"
        cp -a "$POWYX_REPO_ROOT/config" "$POWYX_STAGE_DIR/config"
    }; then
        rm -f -- "$staged_bin"
        _powyx_remove_tree "$POWYX_STAGE_DIR"
        _powyx_error "failed to stage share files"
    fi

    if [[ -e "$POWYX_SHARE_DIR" ]] && ! mv "$POWYX_SHARE_DIR" "$POWYX_PREVIOUS_DIR"; then
        rm -f -- "$staged_bin"
        _powyx_remove_tree "$POWYX_STAGE_DIR"
        _powyx_error "failed to preserve previous share files"
    fi

    if ! mv "$POWYX_STAGE_DIR" "$POWYX_SHARE_DIR"; then
        rm -f -- "$staged_bin"
        _powyx_restore_previous_share
        _powyx_error "failed to activate share files"
    fi

    if [[ ! -f "$POWYX_SHARE_DIR/src/Main.qml" ]]; then
        rm -f -- "$staged_bin"
        _powyx_restore_previous_share
        _powyx_error "installed share files failed verification"
    fi

    if ! mv -f -- "$staged_bin" "$POWYX_BIN_PATH"; then
        rm -f -- "$staged_bin"
        _powyx_restore_previous_share
        _powyx_error "failed to activate installed binary"
    fi

    _powyx_remove_tree "$POWYX_PREVIOUS_DIR"
}

_powyx_install_default_config() {
    mkdir -p "$POWYX_CONFIG_DIR"
    if [[ -f "$POWYX_CONFIG_FILE" ]]; then
        _powyx_log "preserved $POWYX_CONFIG_FILE"
        return
    fi

    install -m 0644 "$POWYX_REPO_ROOT/config/powyx.toml" "$POWYX_CONFIG_FILE"
}

_powyx_uninstall_binary() {
    [[ -e "$POWYX_BIN_PATH" ]] || return 0
    rm -f -- "$POWYX_BIN_PATH"
}

_powyx_uninstall_share() {
    _powyx_remove_tree "$POWYX_SHARE_DIR"
}

_powyx_preserve_config() {
    _powyx_log "preserved $POWYX_CONFIG_FILE"
}