[starship]
os_bg = "c86c57"
os_fg = "1c120f"
dir_bg = "b55b47"
dir_fg = "1c120f"
git_branch_bg = "5a2620"
git_branch_fg = "f2c9c0"
git_status_bg = "5a2620"
git_status_fg = "f2c9c0"
langs_bg = "3a1c18"
langs_fg = "f2c9c0"
time_bg = "231412"
time_fg = "d88a73"
success = "d88a73"
error = "ff6a58"

[tmux]
pane_border = "3a1c18"
pane_active_border = "d88a73"
message_bg = "c86c57"
message_fg = "1c120f"
git_bg = "5a2620"
git_fg = "f7e1db"
host_bg = "3a1c18"
host_fg = "f7e1db"
time_bg = "231412"
time_fg = "d88a73"

[hyprland]
active_border = "d88a73"
inactive_border = "5a2620"

[mako]
bg = "130d0c"
text = "f7e1db"
border = "d88a73"
progress = "b55b47"

[kitty]
bg = "130d0c"
fg = "efd0c7"
cursor = "d88a73"
selection_bg = "b55b47"
selection_fg = "130d0c"
color0 = "130d0c"
color1 = "d64d44"
color2 = "d88a73"
color3 = "c86c57"
color4 = "e0a293"
color5 = "5a2620"
color6 = "3a1c18"
color7 = "efd0c7"
color8 = "231412"
color9 = "ff6a58"
color10 = "e39580"
color11 = "cf745a"
color12 = "f0b5a8"
color13 = "70312a"
color14 = "4b2520"
color15 = "f7e1db"

[wofi]
bg = "130d0c"
border = "d88a73"
input_bg = "3a1c18"
input_border = "5a2620"
text = "efd0c7"
selected_bg = "b55b47"
selected_text = "130d0c"

[theme_names]
nvim = "ashen"

[dircolors]
dir = "d88a73"
link = "cf745a"
archive = "ff6a58"
media = "e0a293"
source = "f7e1db"
exec = "d88a73"
ignored = "3a1c18"
bg = "130d0c"
fg = "efd0c7"
orphan = "ff6a58"