[starship]
os_bg = "018a83"
os_fg = "00140e"
dir_bg = "01736c"
dir_fg = "00140e"
git_branch_bg = "002a24"
git_branch_fg = "8ed7cf"
git_status_bg = "002a24"
git_status_fg = "8ed7cf"
langs_bg = "001e16"
langs_fg = "8ed7cf"
time_bg = "00140e"
time_fg = "01736c"
success = "01736c"
error = "ff4d6d"

[tmux]
pane_border = "001e16"
pane_active_border = "00aaa4"
message_bg = "00aaa4"
message_fg = "00140e"
git_bg = "002a24"
git_fg = "bdf5ef"
host_bg = "001e16"
host_fg = "bdf5ef"
time_bg = "00140e"
time_fg = "018a83"

[hyprland]
active_border = "018a83"
inactive_border = "002a24"

[mako]
bg = "001811"
text = "bdf5ef"
border = "00aaa4"
progress = "018a83"

[kitty]
bg = "00140e"
fg = "8ed7cf"
cursor = "018a83"
selection_bg = "01736c"
selection_fg = "00140e"
color0 = "00140e"
color1 = "ff4d6d"
color2 = "01736c"
color3 = "01736c"
color4 = "018a83"
color5 = "002a24"
color6 = "001e16"
color7 = "8ed7cf"
color8 = "00140e"
color9 = "ff4d6d"
color10 = "01736c"
color11 = "01736c"
color12 = "018a83"
color13 = "002a24"
color14 = "001e16"
color15 = "8ed7cf"

[wofi]
bg = "00140e"
border = "018a83"
input_bg = "001e16"
input_border = "002a24"
text = "8ed7cf"
selected_bg = "01736c"
selected_text = "00140e"

[theme_names]
nvim =  "gruvbox"

[dircolors]
dir = "00aaa4"
link = "7fbcb3"
archive = "018a83"
media = "7fbcb3"
source = "00aaa4"
exec = "018a83"
ignored = "001e16"
bg = "00140e"
fg = "8ed7cf"
orphan = "ff4d6d"
