[starship]
os_bg = "b8bab4"
os_fg = "080909"
dir_bg = "858983"
dir_fg = "080909"
git_branch_bg = "444743"
git_branch_fg = "d9d9d3"
git_status_bg = "2b2d2b"
git_status_fg = "b8bab4"
langs_bg = "191b1a"
langs_fg = "a9aca6"
time_bg = "0b0c0c"
time_fg = "858983"
success = "b8bab4"
error = "a64a40"

[tmux]
pane_border = "2b2d2b"
pane_active_border = "b8bab4"
message_bg = "b8bab4"
message_fg = "080909"
git_bg = "444743"
git_fg = "e1e0da"
host_bg = "242624"
host_fg = "c6c7c1"
time_bg = "0b0c0c"
time_fg = "959992"

[hyprland]
active_border = "b8bab4"
inactive_border = "3b3e3a"

[mako]
bg = "0b0c0c"
text = "d9d9d3"
border = "9fa29c"
progress = "737871"

[kitty]
bg = "080909"
fg = "d0d0ca"
cursor = "b8bab4"
selection_bg = "3d403c"
selection_fg = "e8e7e0"
color0 = "080909"
color1 = "a64a40"
color2 = "87917b"
color3 = "a19369"
color4 = "707d82"
color5 = "86747b"
color6 = "708684"
color7 = "c6c7c1"
color8 = "3a3d39"
color9 = "c45d52"
color10 = "a6b197"
color11 = "c0ad75"
color12 = "8d9ba0"
color13 = "a28b94"
color14 = "8ca3a0"
color15 = "e4e3dc"

[wofi]
bg = "080909"
border = "9fa29c"
input_bg = "171918"
input_border = "3b3e3a"
text = "d0d0ca"
selected_bg = "858983"
selected_text = "080909"

[theme_names]
nvim =  "vague"

[dircolors]
dir = "b8bab4"
link = "8f9891"
archive = "a64a40"
media = "a19369"
source = "d0d0ca"
exec = "87917b"
ignored = "4e514d"
bg = "080909"
fg = "d0d0ca"
orphan = "c45d52"