[starship]
os_bg = "f0a8bc"
os_fg = "080e18"
dir_bg = "e08098"
dir_fg = "080e18"
git_branch_bg = "1e3040"
git_branch_fg = "fcd8e4"
git_status_bg = "1e3040"
git_status_fg = "fcd8e4"
langs_bg = "172535"
langs_fg = "fcd8e4"
time_bg = "0d1a28"
time_fg = "f0a8bc"
success = "f0a8bc"
error = "803050"

[tmux]
pane_border = "1e3040"
pane_active_border = "f0a8bc"
message_bg = "f0a8bc"
message_fg = "080e18"
git_bg = "1e3040"
git_fg = "fcd8e4"
host_bg = "172535"
host_fg = "fcd8e4"
time_bg = "080e18"
time_fg = "f0a8bc"

[hyprland]
active_border = "f0a8bc"
inactive_border = "1e3040"

[mako]
bg = "080e18"
text = "f0a8bc"
border = "e08098"
progress = "e08098"

[kitty]
bg = "080e18"
fg = "fcd8e4"
cursor = "f0a8bc"
selection_bg = "e08098"
selection_fg = "080e18"
color0 = "080e18"
color1 = "803050"
color2 = "f0a8bc"
color3 = "e08098"
color4 = "f0a8bc"
color5 = "1e3040"
color6 = "172535"
color7 = "fcd8e4"
color8 = "0d1a28"
color9 = "803050"
color10 = "f0a8bc"
color11 = "e08098"
color12 = "f0a8bc"
color13 = "1e3040"
color14 = "172535"
color15 = "fcd8e4"

[wofi]
bg = "080e18"
border = "f0a8bc"
input_bg = "172535"
input_border = "1e3040"
text = "fcd8e4"
selected_bg = "e08098"
selected_text = "080e18"

[theme_names]
nvim =  "rose-pine"

[dircolors]
dir = "fcd8e4"
link = "f0a8bc"
archive = "d08840"
media = "e08098"
source = "f0a8bc"
exec = "f0a8bc"
ignored = "263848"
bg = "0d1a28"
fg = "fcd8e4"
orphan = "803050"
