[starship]
os_bg = "bcaaa4"
os_fg = "090c0c"
dir_bg = "d7ccc8"
dir_fg = "3e2723"
git_branch_bg = "8d6e63"
git_branch_fg = "d7ccc8"
git_status_bg = "8d6e63"
git_status_fg = "bcaaa4"
langs_bg = "6d4c41"
langs_fg = "d7ccc8"
time_bg = "3e2723"
time_fg = "bcaaa4"
success = "d7ccc8"
error = "bcaaa4"

[tmux]
pane_border = "6d4c41"
pane_active_border = "bcaaa4"
message_bg = "bcaaa4"
message_fg = "090c0c"
git_bg = "8d6e63"
git_fg = "e3e5e5"
host_bg = "6d4c41"
host_fg = "e3e5e5"
time_bg = "3e2723"
time_fg = "e3e5e5"

[hyprland]
active_border = "bcaaa4"
inactive_border = "8d6e63"

[mako]
bg = "3e2723"
text = "d7ccc8"
border = "8d6e63"
progress = "bcaaa4"

[kitty]
bg = "3e2723"
fg = "d7ccc8"
cursor = "bcaaa4"
selection_bg = "d7ccc8"
selection_fg = "3e2723"
color0 = "3e2723"
color1 = "bcaaa4"
color2 = "d7ccc8"
color3 = "d7ccc8"
color4 = "bcaaa4"
color5 = "8d6e63"
color6 = "6d4c41"
color7 = "d7ccc8"
color8 = "3e2723"
color9 = "bcaaa4"
color10 = "d7ccc8"
color11 = "d7ccc8"
color12 = "bcaaa4"
color13 = "8d6e63"
color14 = "6d4c41"
color15 = "d7ccc8"

[wofi]
bg = "3e2723"
border = "bcaaa4"
input_bg = "6d4c41"
input_border = "8d6e63"
text = "d7ccc8"
selected_bg = "d7ccc8"
selected_text = "3e2723"

[theme_names]
nvim =  "kanagawa-dragon"

[dircolors]
dir = "d7ccc8"
link = "bcaaa4"
archive = "6d4c41"
media = "d7ccc8"
source = "d7ccc8"
exec = "bcaaa4"
ignored = "6d4c41"
bg = "3e2723"
fg = "d7ccc8"
orphan = "bcaaa4"
